//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECAF.INFRASTRUCTURE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public long CommentId { get; set; }
        public string Text { get; set; }
        public Nullable<long> FormId { get; set; }
    
        public virtual Form Form { get; set; }
    }
}
