//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECAF.INFRASTRUCTURE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.CustomerFinances = new HashSet<CustomerFinance>();
        }
    
        public long CustomerId { get; set; }
        public string Name { get; set; }
        public string InvoiceAddress { get; set; }
        public string PostCode { get; set; }
        public Nullable<int> CustomerType { get; set; }
        public string FinanceName { get; set; }
        public string FinanceNumber { get; set; }
        public string FinanceContactEmail { get; set; }
        public Nullable<long> SiteCardId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerFinance> CustomerFinances { get; set; }
        public virtual SiteCard SiteCard { get; set; }
    }
}
