//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECAF.INFRASTRUCTURE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerFinance
    {
        public long CustomerFinanceId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Number { get; set; }
        public Nullable<long> CustomerId { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
