//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECAF.INFRASTRUCTURE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ECAFEntities : DbContext
    {
        public ECAFEntities()
            : base("name=ECAFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<CustomerFinance> CustomerFinances { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<EcafForm> EcafForms { get; set; }
        public virtual DbSet<FacilitiesManager> FacilitiesManagers { get; set; }
        public virtual DbSet<Form> Forms { get; set; }
        public virtual DbSet<SiteCardAmount> SiteCardAmounts { get; set; }
        public virtual DbSet<SiteCardCharge> SiteCardCharges { get; set; }
        public virtual DbSet<SiteCardData> SiteCardDatas { get; set; }
        public virtual DbSet<SiteCard> SiteCards { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
    }
}
