//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECAF.INFRASTRUCTURE
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcafForm
    {
        public long EcafFormId { get; set; }
        public string Name { get; set; }
        public string PinNumber { get; set; }
        public Nullable<bool> NewContract { get; set; }
        public string SiteName { get; set; }
        public string Position { get; set; }
        public Nullable<bool> Promotion { get; set; }
        public Nullable<int> WeeklyHours { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<bool> BranchManager { get; set; }
        public Nullable<bool> HolidayManager { get; set; }
        public string HolidayYear { get; set; }
        public string HolidayRule { get; set; }
        public Nullable<int> HolidayEntitlement { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<long> FormId { get; set; }
    
        public virtual Form Form { get; set; }
    }
}
