//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECAF.INFRASTRUCTURE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public long EventId { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        public Nullable<int> EventLength { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
