//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECAF.INFRASTRUCTURE
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormPdf
    {
        public long Id { get; set; }
        public Nullable<long> FormId { get; set; }
        public string PdfPath { get; set; }
        public string SubmitterId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
