//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECAF.INFRASTRUCTURE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteCardCharge
    {
        public long SiteCardChargesId { get; set; }
        public string Position { get; set; }
        public Nullable<int> WeeklyHours { get; set; }
        public Nullable<int> ChargeRate { get; set; }
        public Nullable<int> PayRate { get; set; }
        public Nullable<int> AdHocChargeRate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<long> SiteCardId { get; set; }
    
        public virtual SiteCard SiteCard { get; set; }
    }
}
