//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECAF.INFRASTRUCTURE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteCardData
    {
        public long SiteCardDataId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<long> SiteCardId { get; set; }
    
        public virtual SiteCard SiteCard { get; set; }
    }
}
