//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECAF.INFRASTRUCTURE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteCardAmount
    {
        public long SiteCardAmountId { get; set; }
        public Nullable<int> BillingType { get; set; }
        public Nullable<int> AnnualCharge { get; set; }
        public Nullable<int> AnnualBHCharge { get; set; }
        public Nullable<int> TotalAnnual { get; set; }
        public Nullable<int> ChargePerPeriod { get; set; }
        public Nullable<long> SiteCardId { get; set; }
    
        public virtual SiteCard SiteCard { get; set; }
    }
}
