//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECAF.INFRASTRUCTURE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SiteCard()
        {
            this.Customers = new HashSet<Customer>();
            this.FacilitiesManagers = new HashSet<FacilitiesManager>();
            this.SiteCardAmounts = new HashSet<SiteCardAmount>();
            this.SiteCardCharges = new HashSet<SiteCardCharge>();
            this.SiteCardDatas = new HashSet<SiteCardData>();
        }
    
        public long SiteCardId { get; set; }
        public string Name { get; set; }
        public string PostCode { get; set; }
        public string Address { get; set; }
        public Nullable<int> SiteCardType { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public Nullable<bool> IsAdHocCardsAttatched { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> FormId { get; set; }
        public Nullable<long> SiteCardAmountId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<long> FacilitiesManagerId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacilitiesManager> FacilitiesManagers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteCardAmount> SiteCardAmounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteCardCharge> SiteCardCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteCardData> SiteCardDatas { get; set; }
        public virtual SiteCard SiteCards1 { get; set; }
        public virtual SiteCard SiteCard1 { get; set; }
    }
}
